### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by PaszekDevv** [PaszekDev/mizu#56]
Add translation everywhere it is possible, in translate folder you have 2 JSON files.
1. Find text,button or everything what we need to translate
2. Add translation in pl-PL.JSON and en-EN.JSON like existed examples
3. In found item insert {{ 'translate_name' | translate }}

example in login-grid.component.html

**Comment by phanidhar-reddy** [comment]
hey can i work on this and be a part of your team

**Comment by phanidhar-reddy** [comment]
Sure , please let me know once the project ends . I have experience developing  spring boot applications
